# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea577fcae4c30554fd58f2d046200472c8b20e5eb526a3b01db5ced1ed1db14abe475c0cf038648c1e7fe5e98170674d0f7108d2218f81ca4619220c6d6fe2b

test:
  secret_key_base: 0408ae56b8a6408137cc87f0a06f593405b25f2e3693a337e0a4b4bb01511c381ae6d0b0fd58d5270f96a2468e47fc7925da343e22b5ce31ace1a2f1871c03d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
